{
 "title": "Pod Run Times",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "EBS Backed Pod Durations",
   "type": "bargauge",
   "gridPos": { "h": 32, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_completion_time{namespace=\"ebs-backed-workspace\"} - kube_pod_start_time{namespace=\"ebs-backed-workspace\"})"
    }
   ]
  },
  {
   "title": "Memory Backed Pod Durations",
   "type": "bargauge",
   "gridPos": { "h": 32, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_completion_time{namespace=\"memory-backed-workspace\"} - kube_pod_start_time{namespace=\"memory-backed-workspace\"})"
    }
   ]
  },
  {
   "title": "Workspace to S3 Pod Durations",
   "type": "bargauge",
   "gridPos": { "h": 32, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_completion_time{namespace=\"workspace-direct-to-s3\"} - kube_pod_start_time{namespace=\"workspace-direct-to-s3\"})"
    }
   ]
  },
  {
   "title": "Workspace to FSx Pod Durations",
   "type": "bargauge",
   "gridPos": { "h": 32, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_completion_time{namespace=\"workspace-to-fsx\"} - kube_pod_start_time{namespace=\"workspace-to-fsx\"})"
    }
   ]
  }
 ]
}